language: node_js
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm install -g coveralls
  - npm install -g codecov.io
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
  - cat ./coverage/lcov.info | codecov
  - npm run filesize

# Allow Travis tests to run in containers.
sudo: false
